export const QUOTE_CRITERIA = [
  ["Périmètre", "Objectifs métier et indicateurs de départ", 4],
  ["Périmètre", "Inventaire des pages et gabarits", 4],
  ["Périmètre", "Fonctionnalités et cas limites", 4],
  ["Périmètre", "Exclusions explicites", 3],
  ["Périmètre", "Options séparées du socle", 2],
  ["Périmètre", "Critères de recette mesurables", 3],
  ["Périmètre", "Appareils et responsive couverts", 2],
  ["Périmètre", "Navigateurs supportés", 2],
  ["Contenus", "Responsable de la rédaction", 2],
  ["Contenus", "Migration et intégration des contenus", 2],
  ["Contenus", "Images, droits et optimisation", 1],
  ["Contenus", "Langues et traductions", 1],
  ["SEO et données", "Inventaire des URL existantes", 4],
  ["SEO et données", "Plan de redirections", 3],
  ["SEO et données", "Métadonnées et données structurées", 2],
  ["SEO et données", "Sitemap, robots et indexabilité", 2],
  ["SEO et données", "Analytics, consentement et plan de marquage", 3],
  ["Design", "Écrans réellement conçus", 3],
  ["Design", "États vides, erreurs et chargements", 2],
  ["Design", "Objectif d'accessibilité et preuves", 3],
  ["Design", "Composants et règles réutilisables", 2],
  ["Technique", "Hébergement et environnements", 3],
  ["Technique", "Budget de performance et mesure", 3],
  ["Technique", "Correctifs de sécurité et dépendances", 3],
  ["Technique", "Sauvegardes et restauration testée", 2],
  ["Technique", "Supervision et alertes", 2],
  ["Gouvernance", "Planning, jalons et dépendances client", 3],
  ["Gouvernance", "Livrables à chaque jalon", 2],
  ["Gouvernance", "Procédure de changement et prix", 2],
  ["Gouvernance", "Rôles, interlocuteurs et sous-traitance", 2],
  ["Exploitation", "Maintenance corrective", 3],
  ["Exploitation", "Évolutions et taux/jours inclus", 2],
  ["Exploitation", "Délais de prise en charge et SLA", 3],
  ["Exploitation", "Tous les coûts récurrents", 2],
  ["Propriété et sortie", "Dépôt du code source", 3],
  ["Propriété et sortie", "Comptes et identifiants au nom du client", 3],
  ["Propriété et sortie", "Licences et droits cédés", 2],
  ["Propriété et sortie", "Export des données et contenus", 2],
  ["Propriété et sortie", "Clause et coût de réversibilité", 2],
  ["Propriété et sortie", "Documentation et formation", 2],
] as const;

export const QUOTE_CRITERIA_TOTAL_WEIGHT = QUOTE_CRITERIA.reduce(
  (total, criterion) => total + criterion[2],
  0,
);
