export const techFaqHtml = `
<!-- FAQ TECHNIQUE CONTENU VIDÉO -->
<section class="cv-tfaq">
  <div class="wrap">
    <div class="section-head reveal">
      <div class="left"><div class="eyebrow">— Production &amp; droits</div><h2>Les détails à fixer<br>dans la proposition.</h2></div>
      <div class="right">La pile d'outils n'est pas une preuve de compétence. Nous demandons au spécialiste nommé de préciser son workflow, ses licences et ses limites avant signature.</div>
    </div>
    <div class="cv-tfaq-list reveal reveal-d-1">
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-1">Quels outils seront utilisés ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-1" hidden>Premiere Pro, DaVinci Resolve, After Effects, Rive ou d'autres outils peuvent convenir. La proposition retient uniquement ceux que l'intervenant sait effectivement exploiter et qui correspondent aux formats attendus.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-2">Comment l'IA peut-elle intervenir ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-2" hidden>Transcription, recherche d'angles ou pré-tri peuvent être assistés. Aucun clone vocal ou avatar n'est utilisé sans consentement écrit, et aucun contenu synthétique n'est présenté comme une prise de vue réelle.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-3">Votre charte IA est-elle publiée ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-3" hidden>Non&nbsp;: aucune page publique « charte-ia » ni annexe universelle n'existe aujourd'hui. Les principes applicables sont résumés ici et doivent être repris dans le devis ou une annexe signée si le projet utilise de l'IA générative.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-4">Comment fixer les formats de livraison ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-4" hidden>Résolution, ratio, codec, poids, sous-titres, master et fichiers sources sont listés canal par canal. Les spécifications des plateformes sont revérifiées au moment du projet.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-5">Comment dimensionner une cadence élevée ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-5" hidden>Un test pilote valide d'abord le temps réel de script, tournage, montage et correction. La capacité, les noms et le statut des intervenants sont ensuite écrits au devis&nbsp;; aucune équipe de cinq postes n'est présumée.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-6">Qui porte les licences et droits à l'image ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-6" hidden>Le devis identifie les contenus fournis par le client, les licences achetées, les autorisations d'image et les limites de transfert. Une bibliothèque ou un abonnement tiers n'est jamais présenté comme automatiquement cessible.</div></div>
      <div class="faq-item"><button type="button" class="faq-q" aria-expanded="false" aria-controls="faq-a-video-tech-7">Où le tournage a-t-il lieu ?<span class="ic"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg></span></button><div class="faq-a" id="faq-a-video-tech-7" hidden>Chez le client, dans un lieu loué ou chez un partenaire identifié. Bassens est l'adresse de l'entreprise, pas la preuve d'un studio équipé. Lieu, matériel, assurance et frais sont validés avant commande.</div></div>
    </div>
  </div>
</section>
`;
